Variable block size logic does not work
pin/tftp pull request #61
Opened 2021-01-25 17:12 UTC by mtniehaus

When using the latest code from /pin/tftp, the block size used for tftp transfers (at least on a Windows Server 2016 OS) would always be negotiated by the go logic to 512 bytes, even when the client would indicate that it supports larger block sizes.

The logic was modified to use the largest possible block size, either as configured by callers to the go routines, or as limited by the client options specified to the service.

2021-03-26 02:36 UTC, qin-nz requested changes

2021-03-26 02:36 UTC, qin-nz commented on go.mod
> +module github.com/mtniehaus/tftp/v2
the module name should NOT be changed

2022-07-19 12:17 UTC, pin commented on go.mod
> +module github.com/mtniehaus/tftp/v2
I will merge and then fix real quick.

2022-07-19 12:18 UTC, pin commented on go.mod
> +module github.com/mtniehaus/tftp/v2
But good catch, thank you @qin-nz

2022-07-19 12:18 UTC, pin commented
Thanks @mtniehaus!

2022-07-19 12:18 UTC, merged